n1 = input('Digite a primeira tarefa: ')
n2 = input('Digite a segunda tarefa: ')
n3 = input('Digite a terceira tarefa: ')
n4 = input('Digite a quarta tarefa: ')
n5 = input('Digite a quinta tarefa: ')
n6 = input('Digite a sexta tarefa: ')
n7 = input('Digite a setima tarefa: ')
n8 = input('Digite a oitava tarefa: ')
n9 = input('Digite a nona tarefa: ')
n10 = input('Digite a decima tarefa: ')

print('a primeira tarefa é: ', n1)
print('a segunda tarefa é:', n2)
print('a terceira tarefa é: ', n3)
print('a quarta tarefa é: ', n4)
print('a quinta tarefa é: ', n5)
print('a sexta tarefa é: ', n6)
print('a setima tarefa é: ', n7)
print('a oitava tarefa é: ', n8)
print('a nona tarefa é: ', n9)
print('a decima tarefa é:', n10)